### ISSUE TITLE
Message flood protection kick player from lobby 

### ISSUE THREAD

**Issue by daufinsyd** [beyond-all-reason/BYAR-Chobby#268] opened 2022-09-30 15:42 UTC
Hi :)

When my friend changes settings for a play (lots of settings) and click on "Apply" he we is kicked because of:
Kicking from battle (battle lobby message flood protection).

He is the boss, so I guess all the changes he made are sent once he clicks on apply which is triggering the flood prevention message.

**Comment by AntlerForce** [comment] 2024-11-26 06:14
Duplicate of https://github.com/beyond-all-reason/BYAR-Chobby/issues/716

**Closed by AntlerForce** 2024-11-26 06:14 UTC
Labels: bug
